### ISSUE TITLE
Audio digital objects need the href to be a handle

### ISSUE THREAD

**Issue by lhenze** [nyu-acm/Omega-EAD#1]
Hi,
I see for this audio-service digital object,
https://github.com/nyu-acm/Omega-EAD/blob/main/Omega-EAD.xml#L315
That the referenced link is an aeon link.
This is true for all 6 audio-service digital objects in the EAD.

For this object type (digitized audio available online) we are expecting a handle, for example, 
http://hdl.handle.net/2333.1/9kd51f9f
That way we can embed the actual resource, and have a unique identifier for several other purposes.

**Comment by lhenze** [comment]
Sorry, that was a strange example of a handle, since it resolves to an image resource. 
Here's an example handle for an audio-service object. http://hdl.handle.net/2333.1/7h44j74d

**Comment by weatherlys** [comment]
OK! I fixed most digital object links but left one Aeon link in place (we will have hundreds in existing finding aids). There are now examples of audio-service, video-service, and image-service digital objects with handles.

**Comment by lhenze** [comment]
Great, thanks.
